import { motion } from "framer-motion";
import { BookOpen, Brain, ClipboardList, CalendarDays } from "lucide-react";

const features = [
  {
    icon: BookOpen,
    title: "Upload Notes",
    description:
      "Drop handwritten or typed notes — Vidyalaya digitizes, organizes, and indexes them instantly for quick retrieval.",
    accent: "hsl(185, 48%, 50%)",
  },
  {
    icon: Brain,
    title: "AI Summaries",
    description:
      "Get concise, intelligent summaries of any subject, chapter, or topic generated by our cutting-edge AI engine.",
    accent: "hsl(9, 70%, 54%)",
  },
  {
    icon: ClipboardList,
    title: "Smart Quizzes",
    description:
      "Auto-generated quizzes that adapt to your learning pace, focusing on your weak areas to sharpen recall.",
    accent: "hsl(36, 30%, 72%)",
  },
  {
    icon: CalendarDays,
    title: "Exam Planner",
    description:
      "AI builds a personalized study schedule based on your exam dates and your actual learning velocity.",
    accent: "hsl(185, 48%, 50%)",
  },
];

const FeaturesSection = () => {
  return (
    <section
      id="features"
      className="relative py-32 overflow-hidden"
      style={{ backgroundColor: "hsl(34, 32%, 84%)" }}
    >
      {/* Single lightweight grain layer */}
      <div
        className="absolute inset-0 pointer-events-none grain-coarse"
        style={{ opacity: 0.06, mixBlendMode: "multiply", zIndex: 1 }}
      />

      {/* Radial vignette — CSS only, no JS */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          background:
            "radial-gradient(ellipse at center, transparent 55%, hsla(30,25%,12%,0.08) 100%)",
          zIndex: 2,
        }}
      />

      {/* Diagonal bands — static, no animation (performance fix) */}
      <div
        className="absolute hidden md:block"
        style={{
          backgroundColor: "hsl(9, 70%, 54%)",
          opacity: 0.13,
          width: "35vw",
          height: "120vh",
          top: "-20vh",
          right: "-8vw",
          transform: "rotate(-22deg)",
          zIndex: 0,
        }}
      />
      <div
        className="absolute hidden md:block"
        style={{
          backgroundColor: "hsl(185, 48%, 50%)",
          opacity: 0.1,
          width: "10vw",
          height: "120vh",
          top: "-20vh",
          right: "22vw",
          transform: "rotate(-22deg)",
          zIndex: 0,
        }}
      />

      <div className="relative z-10 max-w-7xl mx-auto px-6 md:px-12">
        {/* Section header */}
        <motion.div
          className="mb-20"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
        >
          <p
            className="font-sans font-medium uppercase mb-4"
            style={{
              color: "hsl(9, 68%, 48%)",
              fontSize: "0.72rem",
              letterSpacing: "0.26em",
            }}
          >
            What We Offer
          </p>
          <h2
            className="font-serif font-bold leading-[0.95] tracking-tight"
            style={{
              color: "hsl(210, 48%, 22%)",
              fontSize: "clamp(3rem, 7vw, 6rem)",
            }}
          >
            Features
          </h2>
          <p
            className="mt-4 font-sans max-w-lg"
            style={{
              color: "hsl(210, 28%, 38%)",
              fontSize: "clamp(1rem, 1.5vw, 1.12rem)",
            }}
          >
            Everything you need to study smarter, not harder.
          </p>
          <motion.div
            className="mt-6 h-1 rounded-full"
            style={{ backgroundColor: "hsl(9, 68%, 52%)", width: "0%" }}
            whileInView={{ width: "80px" }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.3 }}
          />
        </motion.div>

        {/* Feature cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 lg:gap-8">
          {features.map((feature, i) => (
            <motion.div
              key={feature.title}
              className="group relative p-8 md:p-10 rounded-3xl overflow-hidden cursor-pointer"
              style={{ backgroundColor: "hsl(210, 48%, 24%)" }}
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.55, delay: i * 0.1 }}
              // Removed whileHover for mobile performance — use CSS hover instead
            >
              {/* Static accent circle — no JS animation, pure CSS */}
              <div
                className="absolute rounded-full pointer-events-none"
                style={{
                  backgroundColor: feature.accent,
                  opacity: 0.15,
                  width: "180px",
                  height: "180px",
                  top: "-40px",
                  right: "-40px",
                  zIndex: 1,
                  // CSS-only pulse using filter brightness
                  transition: "opacity 0.3s ease",
                }}
              />

              {/* Content */}
              <div className="relative" style={{ zIndex: 10 }}>
                {/* Icon box — plain div, no AnimatedIcon loop */}
                <div
                  className="w-14 h-14 rounded-2xl flex items-center justify-center mb-6"
                  style={{ backgroundColor: feature.accent }}
                >
                  <feature.icon size={28} color="hsl(210, 48%, 18%)" />
                </div>

                <h3
                  className="font-serif font-bold mb-3"
                  style={{
                    color: "hsl(36, 25%, 91%)",
                    fontSize: "clamp(1.4rem, 2.5vw, 1.75rem)",
                  }}
                >
                  {feature.title}
                </h3>

                <p
                  className="font-sans leading-relaxed"
                  style={{
                    color: "hsl(36, 20%, 68%)",
                    fontSize: "clamp(0.9rem, 1.2vw, 1rem)",
                  }}
                >
                  {feature.description}
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FeaturesSection;
