import { motion } from "framer-motion";
import { BookOpen, Brain, ClipboardList, CalendarDays } from "lucide-react";

const features = [
  {
    icon: BookOpen,
    title: "Upload Notes",
    description:
      "Drop handwritten or typed notes — Vidyalaya digitizes, organizes, and indexes them instantly for quick retrieval.",
    accent: "hsl(185, 48%, 50%)",
  },
  {
    icon: Brain,
    title: "AI Summaries",
    description:
      "Get concise, intelligent summaries of any subject, chapter, or topic generated by our cutting-edge AI engine.",
    accent: "hsl(9, 70%, 54%)",
  },
  {
    icon: ClipboardList,
    title: "Smart Quizzes",
    description:
      "Auto-generated quizzes that adapt to your learning pace, focusing on your weak areas to sharpen recall.",
    accent: "hsl(36, 30%, 72%)",
  },
  {
    icon: CalendarDays,
    title: "Exam Planner",
    description:
      "AI builds a personalized study schedule based on your exam dates and your actual learning velocity.",
    accent: "hsl(185, 48%, 50%)",
  },
];

/* Inline multi-layer grain overlay */
const VintageGrain = ({ zBase = 2 }: { zBase?: number }) => (
  <>
    <div
      className="absolute inset-0 pointer-events-none grain-coarse"
      style={{ opacity: 0.34, mixBlendMode: "multiply", zIndex: zBase }}
    />
    <div
      className="absolute inset-0 pointer-events-none grain-fine"
      style={{ opacity: 0.2, mixBlendMode: "multiply", zIndex: zBase + 1 }}
    />
    <div
      className="absolute inset-0 pointer-events-none"
      style={{
        background:
          "linear-gradient(160deg,hsla(34,60%,55%,0.10) 0%,hsla(28,55%,50%,0.06) 50%,hsla(34,60%,45%,0.12) 100%)",
        zIndex: zBase + 2,
      }}
    />
  </>
);

const FeaturesSection = () => {
  return (
    <section
      id="features"
      className="relative py-32 overflow-hidden"
      style={{ backgroundColor: "hsl(34, 32%, 84%)" }}
    >
      <VintageGrain zBase={1} />

      {/* Radial vignette */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          background:
            "radial-gradient(ellipse at center, transparent 55%, hsla(30,25%,12%,0.18) 100%)",
          zIndex: 5,
        }}
      />

      {/* Decorative diagonal bands */}
      <motion.div
        className="absolute"
        style={{
          backgroundColor: "hsl(9, 70%, 54%)",
          opacity: 0.13,
          width: "35vw",
          height: "120vh",
          top: "-20vh",
          right: "-8vw",
          transform: "rotate(-22deg)",
          zIndex: 0,
        }}
        animate={{ rotate: [-22, -19, -22] }}
        transition={{ duration: 14, repeat: Infinity, ease: "easeInOut" }}
      />
      <motion.div
        className="absolute"
        style={{
          backgroundColor: "hsl(185, 48%, 50%)",
          opacity: 0.1,
          width: "10vw",
          height: "120vh",
          top: "-20vh",
          right: "22vw",
          transform: "rotate(-22deg)",
          zIndex: 0,
        }}
        animate={{ rotate: [-22, -18, -22] }}
        transition={{ duration: 17, repeat: Infinity, ease: "easeInOut" }}
      />

      <div className="relative z-10 max-w-7xl mx-auto px-6 md:px-12">
        {/* Section header */}
        <motion.div
          className="mb-20"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
        >
          <p
            className="font-sans font-medium uppercase mb-4"
            style={{
              color: "hsl(9, 68%, 48%)",
              fontSize: "0.72rem",
              letterSpacing: "0.26em",
            }}
          >
            What We Offer
          </p>
          <h2
            className="font-serif font-bold leading-[0.95] tracking-tight"
            style={{
              color: "hsl(210, 48%, 22%)",
              fontSize: "clamp(3rem, 7vw, 6rem)",
            }}
          >
            Features
          </h2>
          <p
            className="mt-4 font-sans max-w-lg"
            style={{
              color: "hsl(210, 28%, 38%)",
              fontSize: "clamp(1rem, 1.5vw, 1.12rem)",
            }}
          >
            Everything you need to study smarter, not harder.
          </p>
          <motion.div
            className="mt-6 h-1 rounded-full"
            style={{ backgroundColor: "hsl(9, 68%, 52%)", width: "0%" }}
            whileInView={{ width: "80px" }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.3 }}
          />
        </motion.div>

        {/* Feature cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 lg:gap-8">
          {features.map((feature, i) => (
            <motion.div
              key={feature.title}
              className="group relative p-8 md:p-10 rounded-3xl overflow-hidden cursor-pointer"
              style={{ backgroundColor: "hsl(210, 48%, 24%)" }}
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.55, delay: i * 0.1 }}
              whileHover={{ y: -6, transition: { duration: 0.3 } }}
            >
              {/* Grain on each card */}
              <div
                className="absolute inset-0 pointer-events-none grain-coarse rounded-3xl"
                style={{ opacity: 0.3, mixBlendMode: "multiply", zIndex: 1 }}
              />
              <div
                className="absolute inset-0 pointer-events-none grain-fine rounded-3xl"
                style={{ opacity: 0.18, mixBlendMode: "multiply", zIndex: 2 }}
              />
              <div
                className="absolute inset-0 pointer-events-none rounded-3xl"
                style={{
                  background:
                    "linear-gradient(145deg,hsla(34,55%,50%,0.09) 0%,transparent 60%)",
                  zIndex: 3,
                }}
              />

              {/* Accent circle */}
              <motion.div
                className="absolute rounded-full"
                style={{
                  backgroundColor: feature.accent,
                  opacity: 0.18,
                  width: "180px",
                  height: "180px",
                  top: "-40px",
                  right: "-40px",
                  zIndex: 1,
                }}
                animate={{ scale: [1, 1.15, 1] }}
                transition={{
                  duration: 8 + i * 2,
                  repeat: Infinity,
                  ease: "easeInOut",
                }}
              />

              {/* Content */}
              <div className="relative" style={{ zIndex: 10 }}>
                <div
                  className="w-14 h-14 rounded-2xl flex items-center justify-center mb-6"
                  style={{ backgroundColor: feature.accent }}
                >
                  <feature.icon
                    className="w-7 h-7"
                    style={{ color: "hsl(210, 48%, 18%)" }}
                    strokeWidth={1.8}
                  />
                </div>

                <h3
                  className="font-serif font-bold mb-3"
                  style={{
                    color: "hsl(36, 25%, 91%)",
                    fontSize: "clamp(1.4rem, 2.5vw, 1.75rem)",
                  }}
                >
                  {feature.title}
                </h3>

                <p
                  className="font-sans leading-relaxed"
                  style={{
                    color: "hsl(36, 20%, 68%)",
                    fontSize: "clamp(0.9rem, 1.2vw, 1rem)",
                  }}
                >
                  {feature.description}
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FeaturesSection;
