import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ChevronLeft, Shield } from "lucide-react";
import NavBar from "@/components/NavBar";
import FooterSection from "@/components/FooterSection";

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-[hsl(210,48%,26%)] text-[hsl(36,25%,90%)] font-sans">
      <NavBar />

      <main className="max-w-4xl mx-auto px-6 pt-32 pb-20">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-white/60 hover:text-coral-400 transition-colors mb-8 group"
        >
          <ChevronLeft
            size={20}
            className="group-hover:-translate-x-1 transition-transform"
          />
          Back to Home
        </Link>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white/5 border border-white/10 rounded-[3rem] p-8 md:p-16 backdrop-blur-xl shadow-2xl"
        >
          <div className="flex items-center gap-4 mb-8">
            <div className="w-12 h-12 rounded-2xl bg-coral-500/10 flex items-center justify-center text-coral-500">
              <Shield size={24} />
            </div>
            <h1 className="text-4xl md:text-5xl font-serif font-bold text-white">
              Privacy Policy
            </h1>
          </div>

          <div className="bg-coral-500/10 border border-coral-500/20 rounded-2xl p-6 mb-10">
            <p className="text-coral-400 font-bold uppercase tracking-widest text-[10px] mb-2">
              Hackathon Project Disclaimer
            </p>
            <p className="text-sm text-white/80 leading-relaxed">
              Vidyalaya AI is an academic project developed for a hackathon. By
              using this application, you acknowledge that it is a demonstration
              platform and not a commercial product.
            </p>
          </div>

          <div className="space-y-8 text-white/70 leading-relaxed">
            <section>
              <h2 className="text-2xl font-serif font-bold text-white mb-4">
                1. Data Collection
              </h2>
              <p>
                We collect minimal data necessary for the application's
                functionality:
              </p>
              <ul className="list-disc list-inside mt-4 space-y-2 ml-4">
                <li>
                  Email address and basic profile info for account creation.
                </li>
                <li>PDF documents you upload for AI analysis.</li>
                <li>
                  Analysis results, quizzes, and study plans generated by the
                  AI.
                </li>
              </ul>
            </section>
            <section>
              <h2 className="text-2xl font-serif font-bold text-white mb-4">
                2. Document Storage
              </h2>
              <p>
                Uploaded documents are stored in our secure database provided by
                InsForge. These documents are processed by AI models (Gemini via
                OpenRouter) to generate your study aids. We do not sell or share
                your document content with third-party advertisers.
              </p>
            </section>
            <section>
              <h2 className="text-2xl font-serif font-bold text-white mb-4">
                3. AI Processing
              </h2>
              <p>
                Your document text is transmitted to AI services (like Google
                Gemini) for the sole purpose of extraction and summarization.
                This data is handled according to their respective privacy
                policies regarding API usage.
              </p>
            </section>
            <section>
              <h2 className="text-2xl font-serif font-bold text-white mb-4">
                4. Cookies & Persistence
              </h2>
              <p>
                We use secure, httpOnly cookies to maintain your login session.
                We do not use tracking pixels or third-party marketing cookies
                for cross-site tracking.
              </p>
            </section>
            <section>
              <h2 className="text-2xl font-serif font-bold text-white mb-4">
                5. Your Control
              </h2>
              <p>
                You can delete any uploaded document from your library at any
                time. Deleting a document will permanently remove the file and
                all associated AI-generated results (summaries, quizzes, plans)
                from our database.
              </p>
            </section>
            <section className="pt-8 border-t border-white/5">
              <p className="text-sm italic">
                Last Updated: April 17, 2026
                <br />
                Contact: hackathon-support@vidyalaya.ai
              </p>
            </section>
            Section Content
          </div>
        </motion.div>
      </main>

      <FooterSection />
    </div>
  );
};

export default PrivacyPolicy;
