import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ChevronLeft, FileText } from "lucide-react";
import NavBar from "@/components/NavBar";
import FooterSection from "@/components/FooterSection";

const TermsAndConditions = () => {
  return (
    <div className="min-h-screen bg-[hsl(210,48%,26%)] text-[hsl(36,25%,90%)] font-sans">
      <NavBar />

      <main className="max-w-4xl mx-auto px-6 pt-32 pb-20">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-white/60 hover:text-coral-400 transition-colors mb-8 group"
        >
          <ChevronLeft
            size={20}
            className="group-hover:-translate-x-1 transition-transform"
          />
          Back to Home
        </Link>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white/5 border border-white/10 rounded-[3rem] p-8 md:p-16 backdrop-blur-xl shadow-2xl"
        >
          <div className="flex items-center gap-4 mb-8">
            <div className="w-12 h-12 rounded-2xl bg-coral-500/10 flex items-center justify-center text-coral-500">
              <FileText size={24} />
            </div>
            <h1 className="text-4xl md:text-5xl font-serif font-bold text-white">
              Terms & Conditions
            </h1>
          </div>

          <div className="bg-coral-500/10 border border-coral-500/20 rounded-2xl p-6 mb-10">
            <p className="text-coral-400 font-bold uppercase tracking-widest text-[10px] mb-2">
              Academic & Hackathon Purpose Only
            </p>
            <p className="text-sm text-white/80 leading-relaxed">
              These terms govern the use of Vidyalaya AI for the duration of the
              hackathon evaluation and demonstration period.
            </p>
          </div>

          <div className="space-y-8 text-white/70 leading-relaxed">
            <section>
              <h2 className="text-2xl font-serif font-bold text-white mb-4">
                1. Acceptance of Terms
              </h2>
              <p>
                By accessing Vidyalaya AI, you agree that this is an
                experimental project. You understand that the service is
                provided "as is" and "as available" for demonstration purposes.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-serif font-bold text-white mb-4">
                2. AI Generated Content
              </h2>
              <p>
                The summaries, quizzes, and study plans are generated by
                Artificial Intelligence. While we strive for accuracy, the AI
                may occasionally produce incorrect, incomplete, or biased
                information. Users are advised to verify all critical academic
                information against original sources.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-serif font-bold text-white mb-4">
                3. Prohibited Use
              </h2>
              <p>Users must not:</p>
              <ul className="list-disc list-inside mt-4 space-y-2 ml-4">
                <li>
                  Upload copyrighted material they do not have the right to
                  process.
                </li>
                <li>Attempt to bypass security constraints or rate limits.</li>
                <li>
                  Upload malicious files (malware, viruses) designed to disrupt
                  the service.
                </li>
                <li>
                  Use the app for commercial profit during the hackathon phase.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-serif font-bold text-white mb-4">
                4. Limitation of Liability
              </h2>
              <p>
                The developers of Vidyalaya AI shall not be held liable for any
                loss of data, academic performance results, or any
                direct/indirect damages resulting from the use or inability to
                use this demonstration platform.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-serif font-bold text-white mb-4">
                5. Project Termination
              </h2>
              <p>
                Being a hackathon project, the developers reserve the right to
                modify or terminate the service and delete all stored data at
                any time without prior notice following the conclusion of the
                event evaluation.
              </p>
            </section>

            <section className="pt-8 border-t border-white/5">
              <p className="text-sm italic">
                Last Updated: April 17, 2026
                <br />
                Vidyalaya AI Hackathon Team
              </p>
            </section>
          </div>
        </motion.div>
      </main>

      <FooterSection />
    </div>
  );
};

export default TermsAndConditions;
